# Generated by Django 4.2.9 on 2024-04-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_order_payment_orderreturn_orderpurchase_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpurchase',
            name='qty',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
