# Generated by Django 4.2.9 on 2024-04-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_orderpurchase_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpurchase',
            name='qty',
        ),
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
