# Generated by Django 4.2.9 on 2024-04-22 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('mobile', models.BigIntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('payroll', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mobile', models.BigIntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=20)),
                ('emp_joindate', models.DateField()),
                ('emp_skill', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('amuont', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('weigth', models.BigIntegerField()),
                ('pro_img', models.ImageField(default='NULL', upload_to='pics/')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='COD', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.order')),
            ],
        ),
        migrations.CreateModel(
            name='orderreturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.order')),
            ],
        ),
        migrations.CreateModel(
            name='orderpurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='proid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.product'),
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='COD', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.customer')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.order')),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfgdate', models.DateField()),
                ('qty', models.BigIntegerField(blank=True, null=True)),
                ('batchno', models.BigIntegerField(blank=True, null=True)),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.product')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.customer')),
            ],
        ),
    ]
